import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased tracking-[-0.08em]`}>
        <img
          src="/images/background.png"
          alt="background"
          className="absolute inset-0 bg-cover bg-center bg-no-repeat w-full h-full -z-10"
        />
        {children}
      </body>
    </html>
  );
}
